name: Update spec document because of new spec release

on:
  release:
    types:
      - published

jobs:
  Make-PR:
    name: Make PR on website repository with latest spec release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v2
        with:
          path: spec
          ref: ${{ github.event.release.target_commitish }}
      - name: Checkout Another repository
        uses: actions/checkout@v2
        with:
          repository: asyncapi/website
          path: website
          token: ${{ env.GITHUB_TOKEN }}
      - name: Config git
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
      - name: Make branch in Another repository & Copy files from Current Repo to Another
        working-directory: ./website
        run: |
          git checkout -b spec-release-${{github.event.release.tag_name}}
          mkdir ./pages/docs/specifications/spec-${{github.event.release.tag_name}}
          cp ../spec/spec/* ./pages/docs/specifications/spec-${{github.event.release.tag_name}}
      - name: Copy spec to "latest" directory in case of release
        if: ${{github.event.release.prerelease == false}}
        working-directory: ./website
        run: |
          rm ./pages/docs/specifications/latest/*
          cp ../spec/spec/* ./pages/docs/specifications/latest/
      - name: Commit and push
        working-directory: ./website
        run: |
          git add .
          git commit -m "docs(spec): ${{github.event.release.tag_name}} release"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/website
      - name: Create PR
        working-directory: ./website
        run: |
          gh pr create --title "doc(spec): ${{github.event.release.tag_name}} release" --body "New version of the specification is available and this PR introduces update to specification document on the website" --head "spec-release-${{github.event.release.tag_name}}"
